### ISSUE TITLE
Warning when trying to add new product

### ISSUE THREAD

**Issue by Tzvook** [lokothodida/gs-catalog#12]
when trying to add FIRST new product I get :
## Warning: SimpleXMLElement::saveXML(D:\xampp\htdocs\php\cms\GetSimple\GSBD-33X/data/other/catalog/products/product-1_en.xml) [simplexmlelement.savexml]: failed to open stream: No such file or directory in D:\xampp\htdocs\php\cms\GetSimple\GSBD-33X\plugins\catalog\data.class.php on line 60

creating /data/other/catalog/products/ directory manually solves it ...

**Comment by lokothodida** [comment]
Problem noted on [GetSimple](http://get-simple.info/forums/showthread.php?tid=4807&pid=49282#pid49282) forums as well. Recent commit should solve the problem (fingers crossed).

**Comment by Tzvook** [comment]
I'll try it soon ...
I saw the request for Image picker in the forum and noticed that when I added it to github yesterday it labeled itself as a new branch :-) so you missed it  
https://github.com/Tzvook/gs-catalog/blob/patch-1/catalog/editcategory.php

**Comment by lokothodida** [comment]
Thanks for the fix. Merged the branches.

Also, it should be safe for you to work on a separate language file and for me to merge it into the current branch, so you can do the translation whenever you want. And generally, I'm happier with this codebase, so you can also make fixes where you see obvious bugs.

**Comment by Tzvook** [comment]
Yep - this codebase is great.
but for the image-picker - there were later corrections + a focus request @ the GS forum ( http://get-simple.info/forums/showthread.php?tid=4807&pid=49325#pid49325 ) 
I gave a solution for the focus , but didn't checked it @ all browsers

**Comment by lokothodida** [comment]
Implemented your changes.
